### ISSUE TITLE
Next Irmin release

### ISSUE THREAD

**Issue by zshipko** [andreas/irmin-graphql#9]
Hey @andreas, hope all is well!

We are currently working on the next Irmin release and are interested in moving `irmin-graphql` into the main repository. 

The reason behind this is to be able to keep irmin-graphql up-to-date with new API changes -- we are also hoping to add graphql support to the command line tool for this next release. In other words, we'd like irmin-graphql to be a core part of Irmin, rather than an additional dependency.

Is this something you would be comfortable with?

**Comment by andreas** [comment]
That makes perfect sense, feel free to move `irmin-graphql` into `irmin`.

Regarding the dependency on `cohttp-lwt-unix` (mentioned in [this comment](https://github.com/zshipko/irmin-graphql/commit/3bfd7ab1707929e0ad4a95ea9cfa86ac9e8fcb9c#r30651001)), would you be able to leverage the idea from [this PR](https://github.com/andreas/ocaml-graphql-server/pull/116)?

Btw, I've been playing around with exposing Irmin watches as GraphQL subscriptions -- I'll try share something in the near future.

Lastly, are you on Discord, IRC, Slack or similar? Some of these conversations may be in easier in such a medium rather than pull requests 😄

**Comment by zshipko** [comment]
Great!

It does seem like we could leverage the proposed `graphql-cohttp` library to build `graphql-lwt-mirage` (or something like that). I will take a closer look early next week and comment on that PR if I see any issues. Thanks for pointing it out!

Also, I think irmin watches as subscriptions sounds really cool. I would love to take a look at that when youre ready to share :smiley: 

There is an irmin channel on Slack, which is probably the best place to continue this discussion. I've just invited you, so feel free to reply there.

**Comment by zshipko** [comment]
`irmin-graphql` has just been merged into the main repo 😄 

See: https://github.com/mirage/irmin/pull/558
